### ISSUE TITLE
Release an opam package

### ISSUE THREAD

**Issue by Drup** [smimram/ocaml-glpk#2]
Last version on opam is 0.1.6, which is the one that is broken with recent glpk. :)

Also, to be consistent with other opam packages, I think the name should be simply "glpk".

**Comment by oddg** [comment]
As a temporary fix, we can install the 0.1.8 version with opam by cloning the repo and [creating a local package](https://opam.ocaml.org/doc/Packaging.html#Creatingalocalpackage).

**Comment by smimram** [comment]
I submitted a PR to opam to have 0.1.7: https://github.com/ocaml/opam-repository/pull/7745

**Comment by smimram** [comment]
Opam has now been updated.

**Comment by oddg** [comment]
Thank you

**Comment by oddg** [comment]
Just as note, the current version (0.1.7) is not compatible with glpk:
 - version <= 4.52 as it uses the routine `glp_get_it_cnt` introduced in version 4.53
 - version >= 4.58 as it uses the routine `glp_main` removed in version 4.58

I am running version 4.57 and it works fine!

**Comment by smimram** [comment]
Thanks for letting me know, this should be fixed in 0.1.8.
